# Generated by Django 3.2.7 on 2021-09-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationsMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('negotiation', models.IntegerField()),
                ('owner', models.IntegerField()),
            ],
            options={
                'db_table': 'negotiations_messages',
                'managed': False,
            },
        ),
    ]
